config/routes.rb
Rails.application.routes.draw do
	resources :articles do
		resources :comments
	end	
	resources :tags
	resources :authors
	root 'articles#index'

	resources :author_sessions, only: [ :new, :create, :destroy ]

	get 'login'  => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings

	def tag_list  
		self.tags.collect{|tag| tag.name}.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles, through: :taggings

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_filter :require_login, except: [:show, :index]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id

	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.save
		redirect_to article_path(@article)
	end

	def destroy
		Article.delete(params[:id])
		redirect_to articles_path
	end

	def edit
		@article = Article.find(params[:id])
		# redirect_to article_path(@article)
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)
		redirect_to article_path(@article)
	end


	private 

	def article_params
		params.require(:article).permit(:title, :body, :tag_list)
	end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  before_filter :require_login, except: [:new, :create]

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  before_filter :zero_authors_or_authenticated, only: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :require_login, except: [:create]

	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]
		@comment.save
		redirect_to article_path(@comment.article)
	end

	def destroy
		# Article.delete(params[:id])
		# redirect_to articles_path
	end

	def edit
		# @article = Article.find(params[:id])
		# # redirect_to article_path(@article)
	end

	def update
		# @article = Article.find(params[:id])
		# @article.update(comment_params)
		# redirect_to article_path(@article)
	end


	private 

	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :require_login, only: [:destroy]
	def show
		@tag = Tag.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
	<h4><%= comment.author_name %> Says:</h4>
	<p class="comment"><%= comment.body %></p>
	<!-- <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p> -->
	<p>Posted at: <%= comment.created_at.strftime("%d %b. %Y, %H:%M") %></p>
</div>

app/views/articles/_form.html.erb
<div id="article_edit">
	<%= form_for(@article) do |f| %>
		<ul>
			<% @article.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
		<p>
			<%= f.label :title %><br />
			<%= f.text_field :title %>
		</p>
		<p>
			<%= f.label :body %><br />
			<%= f.text_area :body %>
		</p>
		<p>
			<%= f.label :tag_list %><br />
			<%= f.text_field :tag_list %>
		</p>
		<p>
			<%= f.submit %>
		</p>
	<% end %>
</div>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>Edit an Article</h1>

	<%= render partial: 'form' %>

</body>
</html>

app/views/articles/index.html.erb
<div class="articles">
	<% if logged_in? %>
		<%= link_to 'Create new article',new_article_path, class: "link" %>
	<!-- <hr> -->
	<% end %>
	<% @articles.reverse.each do |article| %>
		<div class="article">

			<h2><%= article.title %></h2>
			<p id="tags">
				Tags:
				<% article.tags.each do |tag| %>
					<span class="tag">
						<%= link_to tag.name, tag_path(tag) %>
					</span>
				<% end %>
			</p>
			<%= simple_format(article.body[0..300]+"...") %>
			<%= link_to 'Continue Reading...' , article_path(article),class: "link" %>
			<% if logged_in? %>
			<br>
				<%= link_to "Edit", edit_article_path(article),class: "link" %>
				<%= link_to "Delete", article_path(article),class: "link", method: :delete, data: {confirm: "Really delete the article?"} %>
			<% end %>
		</div>
	<% end -%>
</div>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>New Article</h1>
	<%= render partial: 'form' %>

</body>
</html>

app/views/articles/show.html.erb
<div class="navbar">
	<%= link_to 'Articles', articles_path %> >> <%= @article.title %>
</div>
<div class="article">
	<h1><%= @article.title %></h1>
	<p id="tags">
		Tags:
		<% @article.tags.each do |tag| %>
			<span class="tag">
				<%= link_to tag.name, tag_path(tag) %>
			</span>
		<% end %>
	</p>	
	
	<%= simple_format(@article.body) %>
	

	<% if logged_in? %>
	<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>
	<%= link_to "edit", edit_article_path(@article) %>
	<% end %>
</div>
<div id="comments">
	<h3>Comments (<%= @article.comments.size %>) </h3>
	<%= render partial: 'comments/form' %>
	<%= render partial: 'articles/comment', collection: @article.comments %>
</div>

app/views/author_sessions/new.html.erb
<div id="login">
  <h1>Login</h1>

  <%= form_tag author_sessions_path, method: :post do %>
    <div class="field">
      <%= label_tag :email %>
      <br>
      <%= text_field_tag :email %>
      <br/>
    </div>
    <div class="field">
      <%= label_tag :password %>
      <br>
      <%= password_field_tag :password %>
      <br/>
    </div>
    <div class="actions">
      <%= submit_tag "Login" %>
    </div>
  <% end %>

  <%= link_to 'Back', articles_path %>

</div>

app/views/authors/_form.html.erb
<div id="login">
  <%= form_for(author) do |f| %>
    <% if author.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

        <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name:" %><br/>
    <%= f.text_field :author_name , class: "input_area"%>
  </p>
  <p>
    <%= f.label :body, "Your Comment:" %><br/>
    <%= f.text_area :body , class: "input_area"%>
  </p>
  <p>
    <%= f.submit 'Submit' , id: "submit", class: "input_area"%>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blog</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans:400&subset=latin', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Playfair+Display', media: 'all', 'data-turbolinks-track' => true %>

	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
	<%= link_to articles_path do%>
		<div class="logo">
			
		</div>
	<% end %>
</header>
  <div id="container">
	<div id="content">
	  <%= yield %>
	</div>
	  <hr>
	  <footer>
		<% if logged_in? %>
		 	<h5>
				<%= "Logged in as #{current_user.email}" %>
				<%= link_to "(logout)", logout_path %>
		  	</h5>
		<% end %>
	  </footer>
  </div>
</body>
</html>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>